
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Contact from '../components/Contact'
import Expertise from '../components/Expertise'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Logo from '../components/Logo'
import Team from '../components/Team'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-[#f6f6f6] font-bold w-full" >
      <div className="fixed top-0 w-full block bg-[#f6f6f6] z-50">
          <Logo/>
          <Header/>
      </div>
      <div className="relative mt-[calc(30vh)] z-30">
      <About/>

      <Expertise/>
      <Team/>
      <Contact/>
      <Footer/>
      </div>
      
        
     </div>
    </div>
  )
}
